# Métadonnées des 10 Pokémon du projet PokéMAM
# Ordre des classes (index 0 à 9) : Bulbizarre, Salamèche, Carapuce, Pikachu, Rondoudou, Ronflex, Évoli, Lokhlass, Onix, Mewtwo

POKEMON_CLASSES = [
    "Bulbizarre",
    "Salamèche",
    "Carapuce",
    "Pikachu",
    "Rondoudou",
    "Ronflex",
    "Évoli",
    "Lokhlass",
    "Onix",
    "Mewtwo",
]

POKEMON_INFO = {
    "Bulbizarre": {
        "numero": "#001",
        "emoji": "🌿",
        "types": ["Plante", "Poison"],
        "description": "Bulbizarre porte un bulbe sur le dos qui grandit en absorbant la lumière solaire. Il est calme et facile à entraîner.",
        "hp": 45, "atk": 49, "def": 49, "spa": 65, "spd": 65, "spe": 45,
        "legendaire": False,
    },
    "Salamèche": {
        "numero": "#004",
        "emoji": "🔥",
        "types": ["Feu"],
        "description": "La flamme au bout de sa queue indique son état de santé. Elle s'éteint si Salamèche est en danger de mort.",
        "hp": 39, "atk": 52, "def": 43, "spa": 60, "spd": 50, "spe": 65,
        "legendaire": False,
    },
    "Carapuce": {
        "numero": "#007",
        "emoji": "💧",
        "types": ["Eau"],
        "description": "Sa carapace arrondie lui permet de dévier les attaques ennemies. Il nage avec une grande agilité.",
        "hp": 44, "atk": 48, "def": 65, "spa": 50, "spd": 64, "spe": 43,
        "legendaire": False,
    },
    "Pikachu": {
        "numero": "#025",
        "emoji": "⚡",
        "types": ["Électrik"],
        "description": "Il accumule l'électricité dans ses joues et la libère lors d'attaques puissantes. Mascotte de la franchise Pokémon.",
        "hp": 35, "atk": 55, "def": 40, "spa": 50, "spd": 50, "spe": 90,
        "legendaire": False,
    },
    "Rondoudou": {
        "numero": "#039",
        "emoji": "🎵",
        "types": ["Normal", "Fée"],
        "description": "Rondoudou chante une berceuse hypnotique qui endort quiconque l'écoute, même malgré lui.",
        "hp": 115, "atk": 45, "def": 20, "spa": 45, "spd": 25, "spe": 20,
        "legendaire": False,
    },
    "Ronflex": {
        "numero": "#143",
        "emoji": "😴",
        "types": ["Normal"],
        "description": "Il mange 400 kg de nourriture par jour puis s'endort immédiatement. Rien ne peut le réveiller une fois endormi.",
        "hp": 160, "atk": 110, "def": 65, "spa": 65, "spd": 110, "spe": 30,
        "legendaire": False,
    },
    "Évoli": {
        "numero": "#133",
        "emoji": "🦊",
        "types": ["Normal"],
        "description": "Évoli possède un code génétique instable qui lui permet d'évoluer en 8 formes différentes selon son environnement.",
        "hp": 55, "atk": 55, "def": 50, "spa": 45, "spd": 65, "spe": 55,
        "legendaire": False,
    },
    "Lokhlass": {
        "numero": "#131",
        "emoji": "🧊",
        "types": ["Eau", "Glace"],
        "description": "Lokhlass nage dans les mers froides et est réputé pour sauver les naufragés en les portant sur son dos.",
        "hp": 130, "atk": 85, "def": 80, "spa": 85, "spd": 95, "spe": 60,
        "legendaire": False,
    },
    "Onix": {
        "numero": "#095",
        "emoji": "🪨",
        "types": ["Roche", "Sol"],
        "description": "Onix est un serpent de rochers géant qui creuse des tunnels sous terre à plus de 80 km/h.",
        "hp": 35, "atk": 45, "def": 160, "spa": 30, "spd": 45, "spe": 70,
        "legendaire": False,
    },
    "Mewtwo": {
        "numero": "#150",
        "emoji": "🔮",
        "types": ["Psy"],
        "description": "Créé par manipulation génétique à partir de Mew, Mewtwo est le Pokémon le plus puissant jamais conçu.",
        "hp": 106, "atk": 110, "def": 90, "spa": 154, "spd": 90, "spe": 130,
        "legendaire": True,
    },
}

# Couleurs associées aux types pour les graphiques
TYPE_COLORS = {
    "Plante": "#78C850",
    "Poison": "#A040A0",
    "Feu": "#F08030",
    "Eau": "#6890F0",
    "Électrik": "#F8D030",
    "Normal": "#A8A878",
    "Fée": "#EE99AC",
    "Glace": "#98D8D8",
    "Roche": "#B8A038",
    "Sol": "#E0C068",
    "Psy": "#F85888",
    "Vol": "#A890F0",
    "Insecte": "#A8B820",
    "Dragon": "#7038F8",
    "Combat": "#C03028",
    "Spectre": "#705898",
    "Acier": "#B8B8D0",
    "Ténèbres": "#705848",
}
